services:
  - type: web
    name: portfolio-backend
    runtime: docker
    dockerfilePath: ./portfolio-backend/Dockerfile
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
