# Generated by Django 4.2.7 on 2026-06-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_accolade_experiencepoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.URLField(blank=True, null=True),
        ),
    ]
