# Generated by Django 5.2.15 on 2026-06-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_herotypingtext'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceYearCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Startyear', models.DateField()),
                ('Endyear', models.DateField()),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
