# Generated by Django 5.2.15 on 2026-06-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_remove_profile_resume_profile_resume_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='leetcode_url',
            field=models.URLField(blank=True),
        ),
    ]
