# Generated by Django 5.2.15 on 2026-06-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_profile_leetcode_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=50)),
                ('notice_period', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='ExperienceYearCount',
        ),
    ]
